// <auto-generated />
using System;
using System.Collections.Generic;
using Entities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CarServiceContext))]
    [Migration("20230610134839_Updated")]
    partial class Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Car", b =>
                {
                    b.Property<Guid>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdWorkshop")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserIdPerson")
                        .HasColumnType("uuid");

                    b.HasKey("IdCar");

                    b.HasIndex("IdWorkshop");

                    b.HasIndex("UserIdPerson");

                    b.ToTable("Cars");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Car");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.Property<Guid>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DateCompleted")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdCar")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdMechanic")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserIdPerson")
                        .HasColumnType("uuid");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdCar");

                    b.HasIndex("IdMechanic");

                    b.HasIndex("IdUser");

                    b.HasIndex("UserIdPerson");

                    b.ToTable("Orders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Models.Part", b =>
                {
                    b.Property<int>("IdPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPart"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPart");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            IdPart = 1,
                            Name = "Brake pads"
                        },
                        new
                        {
                            IdPart = 2,
                            Name = "Oil filter"
                        },
                        new
                        {
                            IdPart = 3,
                            Name = "Spark plugs"
                        },
                        new
                        {
                            IdPart = 4,
                            Name = "Air filter"
                        },
                        new
                        {
                            IdPart = 5,
                            Name = "Alternator"
                        },
                        new
                        {
                            IdPart = 6,
                            Name = "Battery"
                        },
                        new
                        {
                            IdPart = 7,
                            Name = "Radiator"
                        },
                        new
                        {
                            IdPart = 8,
                            Name = "Water pump"
                        },
                        new
                        {
                            IdPart = 9,
                            Name = "Starter motor"
                        },
                        new
                        {
                            IdPart = 10,
                            Name = "Fuel pump"
                        });
                });

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.Property<Guid>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPerson");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Models.RepairPart", b =>
                {
                    b.Property<int>("IdRepairPart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRepairPart"));

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int>("IdPart")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdRepair")
                        .HasColumnType("uuid");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.HasKey("IdRepairPart");

                    b.HasIndex("IdPart");

                    b.HasIndex("IdRepair");

                    b.ToTable("RepairParts");
                });

            modelBuilder.Entity("Entities.Models.Workshop", b =>
                {
                    b.Property<int>("IdWorkshop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWorkshop"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdWorkshop");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            IdWorkshop = 1,
                            Address = "123 Main Street, Anytown USA",
                            Name = "Car Service Center",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            IdWorkshop = 2,
                            Address = "456 Park Avenue, Anytown USA",
                            Name = "Auto Repair Shop",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            IdWorkshop = 3,
                            Address = "789 Elm Street, Anytown USA",
                            Name = "Mechanic Shop",
                            PhoneNumber = "999-888-7777"
                        });
                });

            modelBuilder.Entity("Entities.Models.CarToBuy", b =>
                {
                    b.HasBaseType("Entities.Models.Car");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int>("Warranty")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("CarToBuy");

                    b.HasData(
                        new
                        {
                            IdCar = new Guid("3c454538-b2b0-4f00-9086-3b3d0b26830a"),
                            IdWorkshop = 1,
                            Model = "Astra",
                            Cost = 50000,
                            Warranty = 3
                        },
                        new
                        {
                            IdCar = new Guid("42a52d8f-42e4-43a3-ba48-79f89226b2b3"),
                            IdWorkshop = 2,
                            Model = "Golf",
                            Cost = 40000,
                            Warranty = 4
                        },
                        new
                        {
                            IdCar = new Guid("636f9723-8eeb-4c07-a039-31056ace4132"),
                            IdWorkshop = 3,
                            Model = "Civic",
                            Cost = 20000,
                            Warranty = 2
                        },
                        new
                        {
                            IdCar = new Guid("08a1f32f-f738-43fb-a34b-f99f0d8b0842"),
                            IdWorkshop = 3,
                            Model = "Fiesta",
                            Cost = 30000,
                            Warranty = 5
                        });
                });

            modelBuilder.Entity("Entities.Models.CarToRepair", b =>
                {
                    b.HasBaseType("Entities.Models.Car");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("IdUser");

                    b.HasDiscriminator().HasValue("CarToRepair");
                });

            modelBuilder.Entity("Entities.Models.Repair", b =>
                {
                    b.HasBaseType("Entities.Models.Order");

                    b.Property<int>("TotalPartCost")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Repair");
                });

            modelBuilder.Entity("Entities.Models.Sale", b =>
                {
                    b.HasBaseType("Entities.Models.Order");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SaleCost")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Sale");
                });

            modelBuilder.Entity("Entities.Models.Mechanic", b =>
                {
                    b.HasBaseType("Entities.Models.Person");

                    b.Property<List<DateTime>>("BookedDates")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone[]");

                    b.Property<int>("IdWorkshop")
                        .HasColumnType("integer");

                    b.HasIndex("IdWorkshop");

                    b.HasDiscriminator().HasValue("Mechanic");

                    b.HasData(
                        new
                        {
                            IdPerson = new Guid("62988d48-7f31-4edb-a188-95dff0a2c4b5"),
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adam",
                            Surname = "Nowak",
                            BookedDates = new List<DateTime>(),
                            IdWorkshop = 1
                        },
                        new
                        {
                            IdPerson = new Guid("1d736f70-76e7-4dab-8815-34e1acd76837"),
                            BirthDate = new DateTime(1992, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ewa",
                            Surname = "Kowalska",
                            BookedDates = new List<DateTime>(),
                            IdWorkshop = 1
                        },
                        new
                        {
                            IdPerson = new Guid("40b00aee-114a-4cc4-b257-317ddf222d41"),
                            BirthDate = new DateTime(1988, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tomasz",
                            Surname = "Lis",
                            BookedDates = new List<DateTime>(),
                            IdWorkshop = 2
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasBaseType("Entities.Models.Person");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Entities.Models.Car", b =>
                {
                    b.HasOne("Entities.Models.Workshop", "Workshop")
                        .WithMany("Cars")
                        .HasForeignKey("IdWorkshop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany("Cars")
                        .HasForeignKey("UserIdPerson");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Entities.Models.Order", b =>
                {
                    b.HasOne("Entities.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("IdCar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Mechanic", "Mechanic")
                        .WithMany("Orders")
                        .HasForeignKey("IdMechanic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Person", "Customer")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserIdPerson");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("Entities.Models.RepairPart", b =>
                {
                    b.HasOne("Entities.Models.Part", "Part")
                        .WithMany("RepairParts")
                        .HasForeignKey("IdPart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Repair", "Repair")
                        .WithMany("RepairParts")
                        .HasForeignKey("IdRepair")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Repair");
                });

            modelBuilder.Entity("Entities.Models.CarToRepair", b =>
                {
                    b.HasOne("Entities.Models.Person", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.Mechanic", b =>
                {
                    b.HasOne("Entities.Models.Workshop", "Workshop")
                        .WithMany("Mechanics")
                        .HasForeignKey("IdWorkshop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Entities.Models.Car", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.Part", b =>
                {
                    b.Navigation("RepairParts");
                });

            modelBuilder.Entity("Entities.Models.Workshop", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Mechanics");
                });

            modelBuilder.Entity("Entities.Models.Repair", b =>
                {
                    b.Navigation("RepairParts");
                });

            modelBuilder.Entity("Entities.Models.Mechanic", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
